server:
  port: 8001

mybatis:
  type-aliases-package: com.zhong.springcloud.pojo
  config-location: classpath:mybatis/mybatis-config.xml
  mapper-locations: classpath:mybatis/mapper/*.xml

spring:
  application:
    name: springcloud-provider-dept # 3个服务的名称一致
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/db01?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: root

# 服务注册到哪里
eureka:
  client:
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/,http://eureka7003.com:7003/eureka/,
  instance:
    instance-id: springcloud-provider-dept-hystrix-8001 # 修改eureka上的默认信息，状态栏位置实例名

# 为监控服务，自定义的一些配置 org.springframework.boot:spring-boot-starter-actuator:2.2.5.RELEASE 这包的作用
info: # 就是状态栏位置实例名的链接点进去的信息
  app.name: zhong-springcloud
  company.name: www.zhong.com